### ISSUE TITLE
Make Footprint Smaller

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/membership-portal#188]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/36285610/214706711-79690c3d-a3d6-428c-b03a-598c2abcf114.png">

- There is wasted space on the right side of the welcome and the name
- Reduce text size and try out having the welcome and the name on the same line and we shall see whether we should keep 2 lines or just 1

**Comment by bobbyyy57** [comment]
Option 1: 

<img width="985" alt="Screenshot 2023-01-26 at 10 04 48 PM" src="https://user-images.githubusercontent.com/72523111/215020360-a6cc2424-d67a-4f7f-a91e-310a420ca246.png">

Option 2: 

<img width="982" alt="Screenshot 2023-01-26 at 10 07 22 PM" src="https://user-images.githubusercontent.com/72523111/215020649-db9bfe2b-6eda-498a-8dd0-0ebef50f5641.png">

Option 3: 

<img width="978" alt="Screenshot 2023-01-26 at 10 12 13 PM" src="https://user-images.githubusercontent.com/72523111/215021279-54f23ebc-8d52-4edf-9a31-18d5bb972061.png">

Option 4: 

<img width="980" alt="Screenshot 2023-01-26 at 10 13 44 PM" src="https://user-images.githubusercontent.com/72523111/215021460-e6847531-9958-4823-af90-5e0d1c4040c4.png">

**Comment by shahdivyank** [comment]
I think option 3 is the way to go. Also try welcome in all lowercase and see which one looks better. Link up the PR and then we are good to go
