### ISSUE TITLE
Make Announcements and Scheduled Meetings Same Height

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/membership-portal#200]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/36285610/215624819-259b9760-ce35-4aa8-a5bc-50480134b0cb.png">

- Slightly misaligned

**Comment by SafeDuck** [comment]
it is the same height on my display
![image](https://user-images.githubusercontent.com/49844738/220485057-fddb3a58-32f5-427c-8f3d-f5d5bf97dc16.png)
