### ISSUE TITLE
Center No Resources Text on Mobile

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/membership-portal#223]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/36285610/217221956-b1369c9f-3872-435e-a520-3af20ce4f946.png">

**Comment by SafeDuck** [comment]
I hope this is what you wanted 
![image](https://user-images.githubusercontent.com/49844738/220486299-13f382b7-043c-4ab1-a26e-232560a30ec6.png)
