### ISSUE TITLE
Remove Extra Spacing

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/membership-portal#423]
<img width="1456" alt="image" src="https://github.com/acm-ucr/membership-portal/assets/36285610/974c0381-c9ca-4617-97f4-2cd2cd8232ce">

**Comment by Bryce7832** [comment]
I do not see a spacing issue on my end. Attached below is the img of the clubroom on my end. 
![No Spacing Issue(Membership Portal)](https://github.com/acm-ucr/membership-portal/assets/79764515/3dadfc5f-8f0c-4717-943d-5b768b0da343)

**Comment by shahdivyank** [comment]
<img width="1512" alt="image" src="https://github.com/acm-ucr/membership-portal/assets/36285610/57bab672-1e16-4ea2-b44c-5a757c796373">

- It is there, try a different screen size, in particular 16:10
