### ISSUE TITLE
Optimize API Call

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/membership-portal#443]
<img width="1512" alt="image" src="https://github.com/acm-ucr/membership-portal/assets/36285610/1d22bf3d-e227-4f51-a270-60eff063789a">

- Currently, we do sorting on browser side (ONLY DO SORTING)
- This can be done via the API call itself, saving some performance on our end
- Refer to this API call for assistance
- https://github.com/Rose-Hacks/discord/blob/dev/bot/scheduler.py#L35-L36

**Comment by Bryce7832** [comment]
![photo](https://github.com/acm-ucr/membership-portal/assets/79764515/5105252d-bab7-4062-91e1-2454575b6528)
