### ISSUE TITLE
Add Logout Button

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/membership-portal#63]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/36285610/194729722-fcf49b28-ffff-4996-83b8-76819352084c.png">

- Add a logout button which takes you to the home route `/`

**Comment by Arnav-Menon** [comment]
actually should I do this one? i saw in the discord that Divyank you asked Ashley Kim to do this?

**Comment by shahdivyank** [comment]
> actually should I do this one? i saw in the discord that Divyank you asked Ashley Kim to do this?

That was regarding the design, Ashley is the UI/UX person who makes our designs so I just asked her to do the designs, but feel free to work on the actual implementation of it
