### ISSUE TITLE
Use the new `Athiti` Font

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/membership-portal#68]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/36285610/194734033-c427e076-6a11-468c-a8ea-dbde1396238a.png">

- Use the font instead of the image
- You can use the font with `font-athiti`
- Delete the image

**Comment by wmx-OwO** [comment]
![image](https://user-images.githubusercontent.com/73259022/194774495-d8628514-0cbb-40df-b1ab-8c08110928e9.png)
![image](https://user-images.githubusercontent.com/73259022/194774497-77466540-4230-4e2f-9887-a53e97336da9.png)
Athiti font looks difference from the font in the picture. Is it okay? or should we use a different font?

**Comment by shahdivyank** [comment]
Yes that is fine! It is supposed to be a font change
